
[env:esp32-devkitlipo]
platform = espressif32
board = esp32-devkitlipo
framework = arduino

lib_deps =
    Links2004/WebSockets

extra_scripts =
    pre:src/web/generate_web.py

build_flags =
    -DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -DWIFI_PASS=\"${sysenv.WIFI_PASS}\"
    